stages:
  - pre_test
  - test
  - deploy

lint:
  image: python:2
  stage: pre_test
  before_script:
    - pip install flake8
  script:
    - make lint

test_2:
  image: python:2
  stage: test
  before_script:
     # Authenticate using the keytab:
    - sudo apt-get update && sudo apt-get install -y krb5-user
    - base64 --decode <(echo "$KRB_KEYTAB_CONTENTS") > $KRB_USERNAME.keytab
    - kinit $KRB_USERNAME@CERN.CH -k -t $KRB_USERNAME.keytab
  script:
    - pip install -r requirements.txt
    - pip install -r ci-deps.txt
    - pytest
    - python setup.py install
    - ./test_get_cookie.sh

test_3:
  stage: test
  image: python:3
  before_script:
    - sudo apt-get update && sudo apt-get install -y krb5-user
     # Authenticate using the keytab:
    - base64 --decode <(echo "$KRB_KEYTAB_CONTENTS") > $KRB_USERNAME.keytab
    - kinit $KRB_USERNAME@CERN.CH -k -t $KRB_USERNAME.keytab
  script:
    - pip install -r requirements.txt
    - pip install -r ci-deps.txt
    - pytest
    - python setup.py install
    - ./test_get_cookie.sh

deploy:
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7

  # only:
  #   - tags

  before_script:
    - yum install -y koji
    - mkdir -p ~/.koji/
    - >
      echo \'[koji]\n
      server = http://koji.cern.ch/kojihub\n
      weburl = http://koji.cern.ch/koji\n
      topurl = http://koji.cern.ch/kojifiles\n
      cert    = /not/existing/file\n\'
      > ~/.koji/config
  script:
    - cat ~/.koji/config

# rpm:
#   image: ubuntu:latest
#   stage: build
#   only:
#     - tags

#   artifacts:
#     paths:
#       - dist/*.rpm
#     name: "dist-$CI_BUILD_REF_NAME"

#   script:
#     - apt-get update && apt-get install -y rpm libxslt-dev libxml2-dev python-pip libkrb5-dev
#     - pip install -r requirements.txt
#     - python setup.py bdist --format=rpm

# install_rpm:
#   stage: deploy
#   image: cern/cc7-base
#   only:
#     - tags

#   before_script:
#     - yum -y update
#     - yum install -y krb5-workstation krb5-libs
#     # Decode the base64-encoded keytab and store it in dbstoragemon.keytab.
#     - base64 --decode <(echo "$KRB_KEYTAB_CONTENTS") > $KRB_USERNAME.keytab
#     # Authenticate using the keytab:
#     - yum install python-requests-kerberos python-requests python2-future
#     - kinit $KRB_USERNAME@CERN.CH -k -t $KRB_USERNAME.keytab

#   script:
#     - rpm -i dist/python-cern-sso-$CI_BUILD_REF_NAME-1.noarch.rpm
#     - cern-get-sso-cookie.py --help
#     - cern-get-sso-cookie.py --kerberos --verbose --url https://dbnas-storage-docs.web.cern.ch
#     - grep -q "dbnas-storage-docs.web.cern.ch" cookies.txt
