install_run:
  image: cern/cc7-base
  script:
    - uname -a
    - yum -y update
    - yum install -y python27-python-pip python27 libxml2-devel libxslt-devel
    - python2.7 setup.py install
    - cern-get-sso-cookie.py --help

lint:
  image: python:latest
  script:
    - pip install -r ci-deps.txt
    - flake8 cern_sso.py
