before_script:
  - apt-get update -qq && apt-get install -y -qq python2.7 python-pip
  - pip install -r ci-deps.txt
  - ./setup.py install
  - pip install pep8

lint:
  script:
    - flake8 cern_sso.py
