lint:
  image: python:latest
  stage: build
  script:
    - pip install -r ci-deps.txt
    - flake8 cern_sso.py

install_run:
  image: cern/cc7-base
  script:
    - uname -a
    - yum -y update
    - yum install -y python-pip python27-python-pip python-setuptools python27 python27-python-setuptools libxml2-devel libxslt-devel gcc gcc-c++ make python27-python-devel python-devel krb5-devel
    - python2.7 -V
    - pip -V
    - pip install twine
    - python2.7 setup.py install
    - cern-get-sso-cookie.py --help

test_2:
  image: python:2
  script:
    - pip install -r requirements.txt
    - pip install -r ci-deps.txt
    - pytest

test_3:
  image: python:3
  script:
    - pip install -r requirements.txt
    - pip install -r ci-deps.txt
    - pytest

rpm:
  image: ubuntu:latest
  stage: deploy
  only:
    - tags

  artifacts:
    paths:
      - dist/*.rpm
    name: "dist-$CI_BUILD_REF_NAME"

  script:
    - apt-get update && apt-get install -y rpm libxslt-dev libxml2-dev python-pip libkrb5-dev
    - pip install twine
    - python setup.py bdist --format=rpm
