stages:
  - pre_test
  - test
  - build
  - deploy

lint:
  image: python:latest
  stage: pre_test
  script:
    - pip install -r ci-deps.txt
    - flake8 cern_sso.py

test_2:
  stage: test
  image: python:2
  script:
    - pip install -r requirements.txt
    - pip install -r ci-deps.txt
    - pytest

test_3:
  stage: test
  image: python:3
  script:
    - pip install -r requirements.txt
    - pip install -r ci-deps.txt
    - pytest

rpm:
  image: ubuntu:latest
  stage: build
  only:
    - tags

  artifacts:
    paths:
      - dist/*.rpm
    name: "dist-$CI_BUILD_REF_NAME"

  script:
    - apt-get update && apt-get install -y rpm libxslt-dev libxml2-dev python-pip libkrb5-dev
    - pip install -r requirements.txt
    - python setup.py bdist --format=rpm

install_rpm:
  stage: deploy
  image: cern/cc7-base
  only:
    - tags

  before_script:
    - yum -y update
    - yum install -y krb5-workstation krb5-libs
    # Decode the base64-encoded keytab and store it in dbstoragemon.keytab.
    - base64 --decode <(echo "$KRB_KEYTAB_CONTENTS") > $KRB_USERNAME.keytab
    # Authenticate using the keytab:
    - yum install python-requests-kerberos python-requests python2-future
    - kinit $KRB_USERNAME@CERN.CH -k -t $KRB_USERNAME.keytab

  script:
    - rpm -i dist/python-cern-sso-$CI_BUILD_REF_NAME-1.noarch.rpm
    - cern-get-sso-cookie.py --help
    - cern-get-sso-cookie.py --kerberos --verbose --url https://dbnas-storage-docs.web.cern.ch
    - grep -q "dbnas-storage-docs.web.cern.ch" cookies.txt
